# Generated by Django 4.1.5 on 2023-01-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('Équipements', 'Équipements'), ('Logements', 'Logements'), ('Urbanisme', 'Urbanisme'), ('Tertiaire', 'Tertiaire'), ('Autre', 'Autre')], default='Équipements', max_length=200)),
                ('info_1', models.CharField(blank=True, max_length=200)),
                ('info_2', models.CharField(blank=True, max_length=200)),
                ('info_3', models.CharField(blank=True, max_length=200)),
                ('info_4', models.CharField(blank=True, max_length=200)),
                ('info_5', models.CharField(blank=True, max_length=200)),
                ('info_6', models.CharField(blank=True, max_length=200)),
                ('info_7', models.CharField(blank=True, max_length=200)),
                ('info_8', models.CharField(blank=True, max_length=200)),
                ('info_9', models.CharField(blank=True, max_length=200)),
                ('info_10', models.CharField(blank=True, max_length=200)),
                ('info_11', models.CharField(blank=True, max_length=200)),
                ('info_12', models.CharField(blank=True, max_length=200)),
                ('info_13', models.CharField(blank=True, max_length=200)),
                ('info_14', models.CharField(blank=True, max_length=200)),
                ('info_16', models.CharField(blank=True, max_length=200)),
                ('classement', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='images/')),
                ('main_big_image', models.ImageField(default='images/defaut.jpg', upload_to='images/')),
                ('image_1', models.ImageField(blank=True, upload_to='images/')),
                ('image_2', models.ImageField(blank=True, upload_to='images/')),
                ('image_3', models.ImageField(blank=True, upload_to='images/')),
                ('image_4', models.ImageField(blank=True, upload_to='images/')),
                ('image_5', models.ImageField(blank=True, upload_to='images/')),
                ('image_6', models.ImageField(blank=True, upload_to='images/')),
                ('image_7', models.ImageField(blank=True, upload_to='images/')),
                ('image_8', models.ImageField(blank=True, upload_to='images/')),
                ('image_9', models.ImageField(blank=True, upload_to='images/')),
                ('image_10', models.ImageField(blank=True, upload_to='images/')),
                ('image_11', models.ImageField(blank=True, upload_to='images/')),
                ('image_12', models.ImageField(blank=True, upload_to='images/')),
                ('image_13', models.ImageField(blank=True, upload_to='images/')),
                ('image_14', models.ImageField(blank=True, upload_to='images/')),
                ('image_15', models.ImageField(blank=True, upload_to='images/')),
                ('image_16', models.ImageField(blank=True, upload_to='images/')),
                ('image_17', models.ImageField(blank=True, upload_to='images/')),
                ('image_18', models.ImageField(blank=True, upload_to='images/')),
                ('image_19', models.ImageField(blank=True, upload_to='images/')),
                ('image_20', models.ImageField(blank=True, upload_to='images/')),
                ('image_21', models.ImageField(blank=True, upload_to='images/')),
                ('image_22', models.ImageField(blank=True, upload_to='images/')),
                ('image_23', models.ImageField(blank=True, upload_to='images/')),
                ('image_24', models.ImageField(blank=True, upload_to='images/')),
                ('image_25', models.ImageField(blank=True, upload_to='images/')),
                ('is_puplished', models.BooleanField(default=True)),
            ],
        ),
    ]
