# Generated by Django 4.1.5 on 2023-01-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_description_about_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
